# Generated by Django 2.2.14 on 2020-07-28 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200702_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Agent',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_agent',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_employer',
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.IntegerField(default=9876),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_office',
            field=models.BooleanField(default=False),
        ),
    ]
