# Generated by Django 2.2.14 on 2020-07-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200728_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_spending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=40)),
                ('quantity', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
    ]
